config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/create'
  root to: 'users#index'
  resources :users do
  	member do
  		get :member_list
  		get :add_friend
  	end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user

  validates :user_id, :friend_id, presence: true
  validates_uniqueness_of :friend_id, scope: :user_id
end

app/models/heading.rb
class Heading < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require 'rest-client'
class User < ApplicationRecord
	before_save :short_website_url
	after_save :add_headings

	has_many :headings, dependent: :destroy

	validates :name, :website_url, presence: true

	def add_headings
		web_url = self.website_url
		title = Nokogiri::HTML::Document.parse(HTTParty.get("#{web_url}").body).css('h1, h2, h3').children.to_s
		self.headings.find_or_create_by(title: title)
	end

	def short_website_url
		payload = { long_url: self.website_url, domain: ENV['shortner_domain'], group_guid: ENV['shortner_group_guid'] }
		response = RestClient.post(ENV['shortner_url'], payload.to_json, Authorization: ENV['shortner_auth_token'], 
			:content_type => 'application/json')
		self.shortened_url = JSON.parse(response)['link']
	end

	def friendships
		Friendship.where("user_id = ? OR friend_id = ?", self.id, self.id)
	end

	def friend_ids
		self.friendships.pluck(:user_id, :friend_id).flatten.uniq - [self.id]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_member, only: [:member_list, :add_friend, :show]

  def index
  	@users = User.all
  end

  def new
  end

  def create
  	@user = User.create(user_params)
  	if @user
  		redirect_to users_path
  		flash[:notice] = 'Member Added.'
  	else
  		flash[:error] = @user.errors.full_messages
  	end
  end

  def show
    if params["search"].present?
      @heading = Heading.where("title ILIKE ?", "%#{params["search"]}%").first
      if @heading
        return if @member.id.eql?(@heading&.user_id)
        
        @expert =  @heading.user
        @linked_friend = FindExpertPath.new(@member.id).path_to(@expert.id)
      end
    end
  end

  def member_list
    @members = User.where.not(id: (@member.friend_ids.push(@member.id)))
  end

  def add_friend
    Friendship.create(user_id: params["id"], friend_id: params["friend_id"])
    redirect_to member_list_user_path(params["id"])
  end

  private

  def user_params
  	params.require(:user).permit(:name, :website_url)
  end

  def find_member
    @member = User.find_by(id: params[:id])
    redirect_to users_path unless @member
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def user_headings(user)
		user.headings.pluck(:title).join(', ').html_safe
	end

	def user_friends(user)
		user_ids = user.friend_ids
		User.where(id: user_ids)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoRackspace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
</style>
</head>
<body>
<div class="offset-1 col-10">

  <h2>Members</h2>
  <%= link_to 'Add Member', new_user_path, class: 'btn btn-primary float-right' %>
  </br></br>
  <table>
    <tr>
      <th>Name</th>
      <th>Web Url</th>
      <th>Friend Count</th>
      <th></th>

    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= link_to user.shortened_url, user.shortened_url, target: :blank %></td>
      <td><%= user.friendships.count %></td>
      <td>
      	<%= link_to 'Add Friend', member_list_user_path(user), class: 'btn btn-primary float-right' %>
      </td>
    </tr>
    <% end if @users.present? %>
  </table>
</div>
</body>
</html>

app/views/users/member_list.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}
</style>
</head>
<body>
<div class="offset-2 col-8">
  <h2>Members</h2>
  <%= link_to 'Back', users_path, class: 'btn btn-primary float-right' %>
  </br></br>
  <table>
    <tr>
      <th>Name</th>
      <th></th>

    </tr>
    <% @members.each do |member| %>
    <tr>
      <td><%= link_to member.name, user_path(member) %></td>
      <td>
      	<%= link_to 'Add', add_friend_user_path(friend_id: member.id), class: 'btn btn-primary' %>
      </td>
    </tr>
    <% end if @members.present? %>
  </table>
</div>
</body>
</html>

app/views/users/new.html.erb
<div class="offset-2 col-6">
	<h2>New Member</h2>
	<%= form_for :user, url: users_path, method: :post do |f| %>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Name</label>
	    <%= f.text_field :name, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Website URL</label>
	    <%= f.text_field :website_url, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	    <%= f.submit "Create", class: 'btn btn-primary' %>
	  </div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="offset-2 col-8">
	<h2>Member Details</h2>
	<%= link_to 'Back', users_path, class: 'btn btn-primary float-right' %>
  <div class="form-group">
    <b>Name: </b>
    <%= @member.name %>
  </div>
  <div class="form-group">
    <b>Website URL: </b>
    <%= link_to @member.website_url, @member.website_url, target: :blank %>
  </div>
  <div class="form-group">
  	<b>Shortened URL: </b>
  	<%= link_to @member.shortened_url, @member.shortened_url, target: :blank %>
  </div>
  <div class="form-group">
  	<b>Headings: </b>
    <%= user_headings(@member) %>
  </div>
	<div class="form-group">
		<b>Friends </b>
	  <% user_friends(@member).each do |member| %>
	  	</br>
	  	<%= link_to member.name, user_path(member) %>
	  <%end%>
  </div>
  <div class="form-group">
  	<b>Find: </b>
    <%= form_tag(user_path(@member), method: :get) do %>
		  <%= text_field_tag :search %>
		  <%= submit_tag 'Search' %>
		<% end %>
  </div>
  <% if @linked_friend.present? %>
	  <div class="form-group">
	  	<b>Result: </b>
	    <%= @linked_friend.join(' -> ') %> (<%= params["search"]%>)
	  </div>
	<%end%>
</div>